# RUN WITH: docker-compose build --progress plain --no-cache

services:

  mysql_db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    
  rust_app:
    depends_on:
      - mysql_db
    image: rust:latest
    working_dir: /app
    volumes:
      - ./api:/app
    command: cargo run
    ports:
      - "80:80"
   
  

# version: '1'
# services:
#   app:
#     depends_on:
#       - mysql_db
#     image: rust:latest
#     build: 
#       context: .
#       dockerfile: ./api/Dockerfile
#     environment:
#       - DOCKER_BUILDKIT=0 
#     volumes:
#       - ../TESTBCC:/TESTBCC
#     ports:
#       - "80:80"
 

#   mysql_db:
#     image: mysql:latest
#     environment:
#       MYSQL_ROOT_PASSWORD: root_password
#       MYSQL_DATABASE: mydatabase
#       MYSQL_USER: user
#       MYSQL_PASSWORD: password
#     ports:
#       - "3306:3306"
  





# version: '1'
# services:

#   dragonfly-db:
#     image: docker.dragonflydb.io/dragonflydb/dragonfly:latest
#     ports:
#       - "6379:6379"
#     networks:
#       - redis-network

#   rust-server:
#     build:
#       context: ./core
#     ports:
#       - "5000:5000"
#     depends_on:
#       - dragonfly-db
#     networks:
#       - redis-network
    
#   ws:
#     build:
#       context: .
#       dockerfile: ./ws/Dockerfile
#     ports:
#       - "10000:10000"
#     depends_on:
#       - dragonfly-db
#     networks:
#       - redis-network
#     deploy:
#       resources:
#         limits:
#           cpus: '0.5'
#           memory: 512M

# networks:
#   redis-network:
