# Build the frontend
FROM node:20-slim AS base
ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
RUN corepack enable
COPY . TESTBCC
WORKDIR /TESTBCC/app

ARG PNPM_CACHE_DIR=/pnpm/store

# Install pnpm
FROM base AS prod-deps
RUN pnpm install --prod --frozen-lockfile

# Build the project
FROM base AS pnpm-builder
RUN pnpm install --frozen-lockfile
RUN pnpm run build

# Copy the compiled frontend to a new image
WORKDIR /TESTBCC
RUN mkdir api/web
RUN mv app/dist/* api/web/.

# Build the Rust API
FROM rust:latest as rust-builder
WORKDIR /
RUN rm -rf /api
RUN mkdir api
COPY --from=pnpm-builder /TESTBCC/api /api
WORKDIR /api
RUN cargo build --release
RUN echo $(ls -1 .)
RUN echo $(ls -1 ..)
RUN echo $(pwd)

# Copy the compiled API to a new image
FROM rust:latest
RUN echo $(ls -1 /api/target/release/api)
RUN echo $(ls -1 /api/target/release)
COPY --from=rust-builder /api/target/release/api /api
CMD ["./api"]
